### PR TITLE
Initial version of the tool

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin8-migration-tool/1)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQtw749DgUfnyJGOQAY:-KQtw749DgUfnyJGOQAZ:bn7i5m3) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L32)):*
> ```Java
>         }
> 
>         String compatServerFilename = m2folder
> ```

Needs to download the dependency 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1)*

**Comment by Legioth** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pom.xml, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyCjukvfjClgNIbFnF:-KQyCjukvfjClgNIbFnG:b2ha1e9) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/pom.xml#L5)):*
> ```XML
>     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
>     <groupId>com.vaadin.framework8</groupId>
> ```

Is `.framework8` really necessary here when almost the same info is also present in the artifact id.

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 43 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyDkbmYbJUZKCXIE7s:-KQyDkbnQ6Cu1Z9Ar6Ml:b-f7mm16) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L43)):*
> ```Java
>         findV7Classes(compatSharedFilename, sharedV7Classes);
>         serverV7UIClasses = serverV7Classes.stream().filter(
>                 cls -> cls.matches("^com\\.vaadin\\.v7\\.ui\\.[^\\.]*$"))
> ```

What does this pattern do that isn't covered by `cls.startsWith("com.vaadin.v7.ui.")`?

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 135 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyF2BP7cBbTlTFsVuG:-KQyF2BQWVXJ0BapnJCR:b5onr4p) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L135)):*
> ```Java
>         for (String v7Class : Stream
>                 .concat(serverV7Classes.stream(), sharedV7Classes.stream())
>                 .collect(Collectors.toList())) {
> ```

Why collect to a list instead of directly doing a reduce over the stream

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 141 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyFGKpnVWeIZHRU9xB:-KQyFGKpnVWeIZHRU9xC:bbhrtga) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L141)):*
> ```Java
>             javaFile = javaFile.replace("import " + comvaadinClass + ";",
>                     "import " + v7Class + ";");
>             javaFile = javaFile.replace("extends " + comvaadinClass + " ",
> ```

What about "implements"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1)*

**Comment by Artur-** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[pom.xml, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyCjukvfjClgNIbFnF:-KQyHx7-GmpUDIHfV7tk:b32wsm) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/pom.xml#L5)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> Is `.framework8` really necessary here when almost the same info is also present in the artifact id.
</details>
no

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQtw749DgUfnyJGOQAY:-KQyxZrRjw2ExzcrqWB-:b-896fix) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L32)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Needs to download the dependency 
</details>
Done.

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 43 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyDkbmYbJUZKCXIE7s:-KQyI0erq3Jp3kA9SyCP:b-dwo06i) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L43)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> What does this pattern do that isn't covered by `cls.startsWith("com.vaadin.v7.ui.")`?
</details>
Avoids matching com.vaadin.v7.ui.Foo.Bar

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 135 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyF2BP7cBbTlTFsVuG:-KQyIIS3QPk2xcFGZNrT:b7o24al) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L135)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> Why collect to a list instead of directly doing a reduce over the stream
</details>
Can't modify `javaFile` from inside a lambda..
Also it does not matter in any way

---

*[src/main/java/com/vaadin/framework8/migrate/Migrate.java, line 141 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQyFGKpnVWeIZHRU9xB:-KQyHs1uhK0yIjs3Ji3N:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/1b6479a645a05a08ee6a61892fa999ea4507995d/src/main/java/com/vaadin/framework8/migrate/Migrate.java#L141)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> What about "implements"
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1)*

**Comment by Legioth** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/framework8/migrate/MavenResolver.java, line 52 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQz3IDPd0fZD24Zae8W:-KQz3IDPd0fZD24Zae8X:buapd7u) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/d3e9a724bf1e209424572b196cb73e11a508ff1e/src/main/java/com/vaadin/framework8/migrate/MavenResolver.java#L52)):*
> ```Java
>                 new OptionalDependencySelector(),
>                 new ExclusionDependencySelector());
>         session.setDependencySelector(depFilter);
> ```

This shouldn't be needed in this case as we don't need any special selector logic for e.g. test dependencies. The defaults produces by `newSession()` should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/framework8/migrate/MavenResolver.java, line 52 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1#-KQz3IDPd0fZD24Zae8W:-KQz97MnMNqj-JdRV3Kp:b-896fix) ([raw file](https://github.com/vaadin/vaadin8-migration-tool/blob/d3e9a724bf1e209424572b196cb73e11a508ff1e/src/main/java/com/vaadin/framework8/migrate/MavenResolver.java#L52)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> This shouldn't be needed in this case as we don't need any special selector logic for e.g. test dependencies. The defaults produces by `newSession()` should be enough.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1)*

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin8-migration-tool/1)*

**Pull request merged**
